import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '/app/home',
    title: 'MENUITEMS.HOME.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.BUY-RECYCOIN.TEXT',
    iconType: 'feather',
    icon: 'shopping-cart',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/app/recycoin',
        title: 'CART-PAGE.BUY.TEXT',
        iconType: 'feather',
        icon: 'dollar-sign',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/app/activate-matrix',
        title: 'CART-PAGE.ACTIVATE-MATRIX.TEXT',
        iconType: 'feather',
        icon: 'grid',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/app/billing-purchases',
    title: 'MENUITEMS.BILLING-MY-PURCHASES.TEXT',
    iconType: 'feather',
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/network',
    title: 'MENUITEMS.NETWORK.TEXT',
    iconType: 'feather',
    icon: 'rss',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/requests',
    title: 'MENUITEMS.REQUEST-PAY.TEXT',
    iconType: 'feather',
    icon: 'shopping-bag',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/wallet',
    title: 'MENUITEMS.WALLET.TEXT',
    iconType: 'feather',
    icon: 'credit-card',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/tickets',
    title: 'MENUITEMS.TOOLS.TEXT',
    iconType: 'feather',
    icon: 'tag',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/app/tickets',
        title: 'MENUITEMS.MY-TICKETS.TEXT',
        iconType: 'feather',
        icon: 'book-open',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/app/academy',
    title: 'EDUCATIONAL-COURSES.ACADEMY-TRADING.TEXT',
    iconType: 'feather',
    icon: 'book-open',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
